version: "3.9"

networks:
  laravel_nuxt:
    driver: bridge

services:
  laravel_app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./laravel:/var/www/app
    ports:
      - "9000:9000"

    networks:
      - laravel_nuxt
    depends_on:
      - laravel_nginx
      - laravel_mysql

  laravel_nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./laravel:/var/www/app
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_nuxt

  laravel_mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: laravel_db
    networks:
      - laravel_nuxt

  nuxt_app:
    build:
      context: ./nuxt3
      dockerfile: Dockerfile
    image: nuxt_app
    container_name: nuxt_app
    command: npm run dev
    volumes:
      - ./nuxt3:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - laravel_nuxt
